# Generated by Django 6.0.3 on 2026-03-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='MundoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(default='🌿', max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('color_class', models.CharField(choices=[('color-1', 'Color 1'), ('color-2', 'Color 2'), ('color-3', 'Color 3'), ('color-4', 'Color 4'), ('color-5', 'Color 5'), ('color-6', 'Color 6')], default='color-1', max_length=10)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Card "Nuestro Mundo"',
                'verbose_name_plural': 'Cards "Nuestro Mundo"',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('tag', models.CharField(help_text='Etiqueta de color (ej: Mascota, Fundador…)', max_length=30)),
                ('tag_color', models.CharField(default='#7ed957', help_text='Color hex del tag', max_length=7)),
                ('tag_txt', models.CharField(default='#0d0a14', help_text='Color hex del texto del tag', max_length=7)),
                ('imagen', models.ImageField(blank=True, help_text='PNG con fondo transparente o de color', null=True, upload_to='personajes/')),
                ('img_filename', models.CharField(blank=True, help_text='Nombre de archivo en static/img/ (ej: mascot-main.png). Se usa si no hay imagen subida.', max_length=100)),
                ('bg_css', models.CharField(default='radial-gradient(circle at 60% 30%, #5b3080, #2d1a45)', help_text='CSS background de la tarjeta de imagen', max_length=200)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Personaje',
                'verbose_name_plural': 'Personajes',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='Cultura, comunidad y conocimiento.', max_length=250)),
                ('eyebrow', models.CharField(default='Sevilla · Noviembre 2025', help_text='Texto pequeño sobre el título del hero', max_length=100)),
                ('cta_texto', models.CharField(default='Descúbrenos', help_text='Botón del hero', max_length=60)),
                ('about_title', models.CharField(default='Una cúpula verde en el corazón de Sevilla', max_length=150)),
                ('about_texto_1', models.TextField(default='Green Dome nació de la convicción de que el conocimiento y la cultura transforman.')),
                ('about_texto_2', models.TextField(default='Creemos en el poder del diálogo abierto, la educación y el arte como herramientas de cambio social.')),
                ('stat_1_num', models.CharField(default='2025', max_length=20)),
                ('stat_1_label', models.CharField(default='Fundación', max_length=50)),
                ('stat_2_num', models.CharField(default='100%', max_length=20)),
                ('stat_2_label', models.CharField(default='Sin ánimo de lucro', max_length=50)),
                ('stat_3_num', models.CharField(default='SVQ', max_length=20)),
                ('stat_3_label', models.CharField(default='Sevilla, España', max_length=50)),
                ('stat_4_num', models.CharField(default='∞', max_length=20)),
                ('stat_4_label', models.CharField(default='Comunidad', max_length=50)),
                ('email', models.EmailField(default='lacupulaverdesv@gmail.com', max_length=254)),
                ('instagram', models.CharField(default='greendome_svq', max_length=60)),
                ('whatsapp', models.CharField(default='+34600000000', help_text='Formato: +34XXXXXXXXX', max_length=20)),
                ('whatsapp_msg', models.CharField(default='Hola Green Dome, quiero información sobre membresía', max_length=200)),
                ('contacto_desc', models.TextField(default='Green Dome es un club privado. Para información sobre membresía contáctanos directamente.')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.CharField(max_length=20, verbose_name='Año / Fecha')),
                ('descripcion', models.TextField()),
                ('destacado', models.BooleanField(default=False, help_text='Marcar si es el hito de Green Dome')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hito del timeline',
                'verbose_name_plural': 'Timeline histórico',
                'ordering': ['orden'],
            },
        ),
    ]
