# Generated by Django 6.0.3 on 2026-03-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_actividad_mundocard_personaje_siteconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo principal PNG (reemplaza el logo del nav, hero y footer). Fondo transparente recomendado.', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='maps_directions_url',
            field=models.URLField(blank=True, default='https://www.google.com/maps/search/Green+Dome+Sevilla', help_text='URL de Google Maps para "Cómo llegar". Abre tu ficha en Google Maps y copia la URL.', max_length=1000),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='maps_embed_url',
            field=models.URLField(blank=True, default='https://maps.google.com/maps?q=Sevilla,+España&z=14&output=embed', help_text='URL del iframe embed. En Google Maps → busca el lugar → Compartir → Insertar un mapa → copia la URL del src=""', max_length=1000),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='maps_review_url',
            field=models.URLField(blank=True, default='', help_text='URL para dejar reseña en Google. En Google Maps → tu ficha → "Obtener enlace para compartir reseñas" → pega aquí.', max_length=1000),
        ),
    ]
