# Generated by Django 6.0.3 on 2026-03-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfig_logo_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='logo_nav',
            field=models.ImageField(blank=True, help_text='Logo PEQUEÑO de la esquina superior izquierda. Puede ser solo el icono/arco sin texto. PNG con fondo transparente.', null=True, upload_to='branding/', verbose_name='Logo Nav (esquina superior)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo GRANDE del centro del hero y footer. PNG recomendado (con texto "GREEN DOME" incluido). Transparente o con fondo.', null=True, upload_to='branding/', verbose_name='Logo Hero (centro)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='maps_directions_url',
            field=models.URLField(blank=True, default='https://www.google.com/maps/place/Asociaci%C3%B3n+Cann%C3%A1bica+Green+Dome/@37.3806919,-5.9812485,17z', help_text='URL de Google Maps para "Cómo llegar". Abre la ficha de Green Dome en Google Maps y copia la URL del navegador.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='maps_embed_url',
            field=models.URLField(blank=True, default='https://maps.google.com/maps?q=37.3806919,-5.9812485&z=17&output=embed', help_text='URL del iframe embed. Cómo obtenerla: Google Maps → busca "Asociación Cannábica Green Dome Sevilla" → Compartir → "Insertar un mapa" → copia SOLO la URL del src=""', max_length=1000),
        ),
    ]
