# Generated by Django 6.0.3 on 2026-03-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteconfig_logo_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='seo_description',
            field=models.TextField(blank=True, default='', help_text='Sobreescribe la meta description. Actualizado automáticamente.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='seo_faq_json',
            field=models.TextField(blank=True, default='', help_text='JSON-LD FAQPage generado por optimize_seo. No edites manualmente.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='seo_keywords',
            field=models.TextField(blank=True, default='', help_text='Keywords para meta keywords. Actualizado automáticamente.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='Sobreescribe el title tag. Se actualiza automáticamente cada día con optimize_seo.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='seo_updated_at',
            field=models.DateTimeField(blank=True, help_text='Última actualización SEO automática.', null=True),
        ),
    ]
