# Generated by Django 6.0.3 on 2026-03-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteconfig_seo_dynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mundocard',
            name='imagen',
            field=models.ImageField(blank=True, help_text='GIF o imagen para la card. Si subes imagen se muestra en lugar del emoji.', null=True, upload_to='mundo/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='maps_embed_url',
            field=models.URLField(blank=True, default='https://maps.google.com/maps?q=37.3806919,-5.9812485&t=&z=17&ie=UTF8&iwloc=&output=embed', help_text='URL del iframe embed. Cómo obtenerla: Google Maps → busca "Asociación Cannábica Green Dome Sevilla" → Compartir → "Insertar un mapa" → copia SOLO la URL del src=""', max_length=1000),
        ),
    ]
