# Generated by Django 6.0.3 on 2026-03-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mundocard_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='hero_bg',
            field=models.ImageField(blank=True, help_text='Imagen o GIF de fondo del hero. Si no subes nada se usa el fondo oscuro por defecto. Recomendado: JPG/PNG ancho (1920x1080 mínimo).', null=True, upload_to='branding/', verbose_name='Fondo del Hero'),
        ),
    ]
