# Generated by Django 6.0.3 on 2026-03-28 04:13
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='imagen',
            field=models.ImageField(
                help_text='Sube la imagen. Una vez guardada, copia su URL y pégala en el contenido '
                          'con <img src="URL" alt="descripción" style="width:100%;border-radius:12px;margin:1.5rem 0;">',
                upload_to='blog/',
                verbose_name='Imagen',
            ),
        ),
    ]
