# Generated by Django 6.0.3 on 2026-04-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_blog_geo_respuesta_rapida'),
        ('core', '0015_clubphoto_blogpost_idioma_blogs_en'),
    ]

    operations = [
    ]
